version: '3.7'
services:
  graphik:
    image: graphikdb/graphik:v0.12.1
    env_file:
      - .env
    ports:
      - "7820:7820"
      - "7821:7821"
    volumes:
      - default:/tmp/graphik2
    networks:
      default:
        aliases:
          - graphikdb
networks:
  default:

volumes:
  default:
